/**
 * Manually defined API functions
 * For endpoints not auto-generated by Orval
 */

import { apiClient } from "./client";

// ============================================
// Types
// ============================================

export interface WatchSubscriptionDto {
  url: string;
  name: string;
  selector: string;
  checkInterval?: number;
}

export interface WatchSubscriptionResult {
  success: boolean;
  subscriptionId?: string;
  urlCount: number;
  error?: string;
}

export interface PreviewSelectorDto {
  url: string;
  selector: string;
}

export interface PreviewSelectorResult {
  success: boolean;
  urlCount: number;
  error?: string;
}

// ============================================
// API Functions
// ============================================

/**
 * Create a watch subscription with selector
 * POST /subscriptions/watch
 */
export async function watchSubscription(
  dto: WatchSubscriptionDto,
): Promise<WatchSubscriptionResult> {
  try {
    const response = await apiClient<{ status: number; data: WatchSubscriptionResult }>(
      "/subscriptions/watch",
      {
        method: "POST",
        body: JSON.stringify({
          url: dto.url,
          name: dto.name,
          selector: dto.selector,
          checkInterval: dto.checkInterval ?? 60,
        }),
      },
    );
    return response.data;
  } catch (error) {
    console.error("[watchSubscription] Error:", error);
    return {
      success: false,
      urlCount: 0,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

/**
 * Preview selector to get URL count
 * POST /subscriptions/preview-selector
 *
 * Note: If this endpoint doesn't exist on the server,
 * we'll skip the preview and let the user proceed directly.
 */
export async function previewSelector(dto: PreviewSelectorDto): Promise<PreviewSelectorResult> {
  try {
    const response = await apiClient<{ status: number; data: PreviewSelectorResult }>(
      "/subscriptions/preview-selector",
      {
        method: "POST",
        body: JSON.stringify({
          url: dto.url,
          selector: dto.selector,
        }),
      },
    );
    return response.data;
  } catch (error) {
    console.error("[previewSelector] Error:", error);
    // Return success with 0 URLs so user can still proceed
    // The actual validation will happen during watch subscription creation
    return {
      success: true,
      urlCount: 0,
      error: error instanceof Error ? error.message : undefined,
    };
  }
}
